### ISSUE TITLE
Patch support

### ISSUE THREAD

**Issue by pedrolucasp** [honza/smithy#15]
While I was writing support for `.patch`, I've stumbled upon go-git not having support for patches.

I opened an [issue](https://github.com/go-git/go-git/issues/260), to either add better support for patches
or writing `format-patch` on go-git. We still can write that manually on smithy, but I would rather wait, 
what do you think?

**Comment by honza** [comment]
It's been over three months, and there has been no response. Maybe we need to write it ourselves?

**Comment by pedrolucasp** [comment]
On Tue, Jun 08, 2021 at 01:24:30AM -0700, Honza Pokorny wrote:

> It's been over three months, and there has been no response. Maybe we
> need to write it ourselves? 

Yeah, I have a WIP patch already. I can send later this week, if you
don't mind.

**Comment by pedrolucasp** [comment]
Opened the #17, let me know if there's any changes you'll like me to do

**Comment by honza** [comment]
Done in #17
