### ISSUE TITLE
Are you planning on tagging a version (or creating a release)?

### ISSUE THREAD

**Issue by herbygillot** [honza/smithy#4]
Hello, and thanks for smithy... just wondering about the above.

**Comment by honza** [comment]
Yes. Do you need one sooner rather than later? Why?

**Comment by herbygillot** [comment]
>  Do you need one sooner rather than later?

No rush on this one.

> Why?

I'm interested in adding smithy to [MacPorts](https://www.macports.org).  A release or branch tag lets us download the appropriate versioned assets, or at least check out via git for building and packaging.

Thanks.

**Comment by honza** [comment]
Just pushed `v0.1.0`

Thanks for your interest!

**Comment by herbygillot** [comment]
Awesome, thank you @honza.

**Comment by herbygillot** [comment]
PR is up: https://github.com/macports/macports-ports/pull/9290

**Comment by herbygillot** [comment]
As a follow-up here, `smithy` can now be installed using MacPorts:

```
sudo port selfupdate
sudo port install smithy
```
