### ISSUE TITLE
make command failing

### ISSUE THREAD

**Issue by johnzan** [honza/smithy#5]
Hi,

when I run the make command I get the following error

```
johnzan@johnzan-ThinkPad-X220:~/Development/GolangDev/smithy$ make

mkdir -p bin

go mod download

go build -o bin/statik /src/github.com/rakyll/statik/statik.go

stat /src/github.com/rakyll/statik/statik.go: directory not found

make: *** [Makefile:12: bin/statik] Error 1
```

**Comment by honza** [comment]
I just pushed a patch that should fix this in 224d6814d266b9fea1d76160e01cc2a7faab17c5. Would you mind testing it?

**Comment by johnzan** [comment]
No prob, I’m out shopping at the moment, will test when I get back.

**Comment by johnzan** [comment]
Just pulled the new version and can confirm its fixed. Closing this one.
Thanks.
