### ISSUE TITLE
cannot build offline cos statik are dependency

### ISSUE THREAD

**Issue by mckaygerhard** [honza/smithy#6]
commit e4b24bd9b86f91e590ca0df270d249039a3503b2 this means golang is not the only dependence, so we need to use also statik from comamnd system to able to produce distribution packages from this great tool!

**Comment by mckaygerhard** [comment]
i need this to produce "debian" directory and also a PKGBUILD file for alpine.. (if does not exist yet)

**Comment by honza** [comment]
Can you post the error log?

What happens when you clone the project, and run `make`?

**Comment by honza** [comment]
Closing as stale
